[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "PlanterCoreClusters_Updated"
versionNumber = "3.0.7"
description = "Allows Planters to be boosted by Core Clusters (configurable % per cluster). Updated for EMU 6.1.3."
websiteUrl = "https://github.com/xXDeath420Xx/TTMod-PlanterCoreClusters"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/net472/PlanterCoreClusters.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
